server:
  port: 6996
spring:
  datasource:
    url: jdbc:derby://localhost:1527/recipe_db;create=true
    driver-class-name:  org.apache.derby.jdbc.ClientDriver
    username: me
    password: mine
  jpa:
    hibernate:
      ddl-auto: update

