INSERT INTO ME.RECIPE (ID, COUNTRY, DESCR, NAME) VALUES (205, 'Bulharsko', 'Jogurt  rozmícháme v litru vody. Poté přidáme nastrouhanou okurku, česnek a sůl. Dochutíme sekaným koprem a oříšky. Podáváme chlazené.
', 'Tarator');
INSERT INTO ME.RECIPE (ID, COUNTRY, DESCR, NAME) VALUES (206, 'Bulharsko', 'Vezmeme jednu kůru, pokropíme ji olejem, na to položíme další kůru a i tu pokropíme olejem. Na jednu polovinu té horní kůry dáme 3 polevkové lžíce náplně. Celé srolujeme. Vytvoříme 6 takových “šišek” a poté je na kulatém povrchu stlačíme do kruhu. Celé potřeme máslem.
Dáme do trouby a pečeme nejprve 20 minut na 180°C, poté 15 minut na 160°C.', 'Banica');
INSERT INTO ME.RECIPE (ID, COUNTRY, DESCR, NAME) VALUES (207, 'Ukrajina', 'Dáme do hrnce vařit na kousky nakrájené maso, až odšumí, vložíme na kostičky nakrájené brambory a na drobno nakrájené čerstvé zelí. Ztlumíme plamen a na mírném ohni povaříme, přidáme bobkový list, polévkové koření. Zvlášť ve slupce uvaříme červenou řepu, nastrouháme na větším struhadle a přidáme na pánev, kde předtím zpěníme cibulku a nastrouhanou čerstvou mrkev, osolíme, opepříme, přidáme rajský protlak, 2 lžíce zakysané smetany a krátce podusíme. Nakonec vše přidáme ke směsi v hrnci, 7-10 minut povaříme a můžeme podávat, ale nejlepší je, až se trochu rozleží.', 'Boršč');
INSERT INTO ME.RECIPE (ID, COUNTRY, DESCR, NAME) VALUES (209, 'Rusko', 'Smícháme mouku, cukr, vanilkový cukr a slunečnicový olej. Poté do misky přidáme ostatní ingredience a mícháme dokud nevznikne těsto bez hrudek. Z vzniklého těsta vytvarujeme kroužky, které položíme na pekáč a ze shora pomažeme žloutkem. Rozehřejeme troubu na 200°C a bubliki pečeme 15-20 minut. ', 'Bubliki');
INSERT INTO ME.RECIPE (ID, COUNTRY, DESCR, NAME) VALUES (210, 'Srbsko', 'Všechny ingredience rozmícháme v míse. Poté položíme plát kore na pekáč a na něj naneseme první vrstvu a na první vrstvu směsi opět položíme jeden plát kore. Takto vrstvíme kore a směs dokud nám směs nedojde. Nakonec pekáč dáme do trouby.', 'Gibanica');
INSERT INTO ME.RECIPE (ID, COUNTRY, DESCR, NAME) VALUES (212, 'Asie', 'Vše smíchat a nechat 30 minut uležet. Vymazat plech sezamovou pastou a těsto dát na plech a rovnou nakrájet, na každý kousek dát mandle. Peče se 150 stupňů zespoda (cca 30 minut) poté vyndat, znovu nakrájet a dopéct zezhora dozlatova.Po upečení - opět rozkrájet a polít cukrovou vodou. Cukrová voda se připraví smícháním a povařením cukru, vody, šťávy z citronu a růžové vody.', 'Harise');
INSERT INTO ME.RECIPE (ID, COUNTRY, DESCR, NAME) VALUES (213, 'Rusko', 'Lilky omyjeme, rozkrájíme na plátky a necháme sušit. Rozehřejeme troubu na 190° a pečeme plátky 30 minut. Omyjeme papriky a i ty dáme péct do trouby (190°) na 15 minut. Poté z lilků a paprik stáhneme kůži a mělce nakrájíme, aby nám vznikla hmota. Nadrobno nakrájíme cibuli, česnek a koriandr. Obě hmoty smícháme a přidáme loupaná rajčata s olejem. Vše promícháme a můžeme podávat.', 'Lilková pomazánka');
INSERT INTO ME.RECIPE (ID, COUNTRY, DESCR, NAME) VALUES (214, 'Srbsko', 'Vše smícháme dohromady a dáme na pekáč do trouby.', 'Prója');
INSERT INTO ME.RECIPE (ID, COUNTRY, DESCR, NAME) VALUES (215, 'Bulharsko', 'Okurku omyjeme, oloupeme a nakrájíme na malé kousky. Rajčata a papriky rovněž omyjeme a nakrájíme, cibuli nakrájíme nadrobno, smícháme s olejem a citronovou šťávou, osolíme, opepříme. Vše promícháme a necháme asi 1 hodinu odležet.', 'Šopský salát');